import Foundation

public class PrincipalAttributes: Decodable {
    public var first_floor_sqft: String?
    public var second_floor_sqft: String?
    public var acres: String?
    public var air_conditioner: String?
    public var arbor_pergola: String?
    public var assessed_improvement_percent: String?
    public var assessed_improvement_value: String?
    public var assessed_land_value: String?
    public var assessed_value: String?
    public var assessor_last_update: String?
    public var assessor_taxroll_update: String?
    public var attic_area: String?
    public var attic_flag: String?
    public var balcony: String?
    public var balcony_area: String?
    public var basement_sqft: String?
    public var basement_sqft_finished: String?
    public var basement_sqft_unfinished: String?
    public var bath_house: String?
    public var bath_house_sqft: String?
    public var bathrooms_partial: String?
    public var bathrooms_total: String?
    public var bedrooms: String?
    public var block1: String?
    public var block2: String?
    public var boat_access: String?
    public var boat_house: String?
    public var boat_house_sqft: String?
    public var boat_lift: String?
    public var bonus_room: String?
    public var breakfast_nook: String?
    public var breezeway: String?
    public var building_definition_code: String?
    public var building_sqft: String?
    public var cabin: String?
    public var cabin_sqft: String?
    public var canopy: String?
    public var canopy_sqft: String?
    public var carport: String?
    public var carport_sqft: String?
    public var cbsa_code: String?
    public var cbsa_name: String?
    public var cellar: String?
    public var census_block: String?
    public var census_block_group: String?
    public var census_fips_place_code: String?
    public var census_tract: String?
    public var central_vacuum: String?
    public var code_title_company: String?
    public var combined_statistical_area: String?
    public var community_rec: String?
    public var company_flag: String?
    public var congressional_district: String?
    public var construction_type: String?
    public var contact_city: String?
    public var contact_crrt: String?
    public var contact_full_address: String?
    public var contact_house_number: String?
    public var contact_mail_info_format: String?
    public var contact_mail_info_privacy: String?
    public var contact_mailing_county: String?
    public var contact_mailing_fips: String?
    public var contact_post_direction: String?
    public var contact_pre_direction: String?
    public var contact_state: String?
    public var contact_street_name: String?
    public var contact_suffix: String?
    public var contact_unit_designator: String?
    public var contact_value: String?
    public var contact_zip: String?
    public var contact_zip4: String?
    public var courtyard: String?
    public var courtyard_area: String?
    public var deck: String?
    public var deck_area: String?
    public var deed_document_page: String?
    public var deed_document_book: String?
    public var deed_document_number: String?
    public var deed_owner_first_name: String?
    public var deed_owner_first_name2: String?
    public var deed_owner_first_name3: String?
    public var deed_owner_first_name4: String?
    public var deed_owner_full_name: String?
    public var deed_owner_full_name2: String?
    public var deed_owner_full_name3: String?
    public var deed_owner_full_name4: String?
    public var deed_owner_last_name: String?
    public var deed_owner_last_name2: String?
    public var deed_owner_last_name3: String?
    public var deed_owner_last_name4: String?
    public var deed_owner_middle_name: String?
    public var deed_owner_middle_name2: String?
    public var deed_owner_middle_name3: String?
    public var deed_owner_middle_name4: String?
    public var deed_owner_suffix: String?
    public var deed_owner_suffix2: String?
    public var deed_owner_suffix3: String?
    public var deed_owner_suffix4: String?
    public var deed_sale_date: String?
    public var deed_sale_price: String?
    public var deed_transaction_id: String?
    public var depth_linear_footage: String?
    public var disabled_tax_exemption: String?
    public var driveway_sqft: String?
    public var driveway_type: String?
    public var effective_year_built: String?
    public var elevation_feet: String?
    public var elevator: String?
    public var equestrian_arena: String?
    public var escalator: String?
    public var exercise_room: String?
    public var exterior_walls: String?
    public var family_room: String?
    public var fence: String?
    public var fence_area: String?
    public var fips_code: String?
    public var fire_resistance_code: String?
    public var fire_sprinklers_flag: String?
    public var fireplace: String?
    public var fireplace_number: String?
    public var first_name: String?
    public var first_name_2: String?
    public var first_name_3: String?
    public var first_name_4: String?
    public var flooring: String?
    public var foundation: String?
    public var game_room: String?
    public var garage: String?
    public var garage_sqft: String?
    public var gazebo: String?
    public var gazebo_sqft: String?
    public var golf_course: String?
    public var grainery: String?
    public var grainery_sqft: String?
    public var great_room: String?
    public var greenhouse: String?
    public var greenhouse_sqft: String?
    public var gross_sqft: String?
    public var guesthouse: String?
    public var guesthouse_sqft: String?
    public var handicap_accessibility: String?
    public var heat: String?
    public var heat_fuel_type: String?
    public var hobby_room: String?
    public var homeowner_tax_exemption: String?
    public var instrument_date: String?
    public var intercom_system: String?
    public var interest_rate_type_2: String?
    public var interior_structure: String?
    public var kennel: String?
    public var kennel_sqft: String?
    public var land_use_code: String?
    public var land_use_group: String?
    public var land_use_standard: String?
    public var last_name: String?
    public var last_name_2: String?
    public var last_name_3: String?
    public var last_name_4: String?
    public var latitude: String?
    public var laundry: String?
    public var lean_to: String?
    public var lean_to_sqft: String?
    public var legal_description: String?
    public var legal_unit: String?
    public var lender_address: String?
    public var lender_address_2: String?
    public var lender_city: String?
    public var lender_city_2: String?
    public var lender_code_2: String?
    public var lender_first_name: String?
    public var lender_first_name_2: String?
    public var lender_last_name: String?
    public var lender_last_name_2: String?
    public var lender_name: String?
    public var lender_name_2: String?
    public var lender_seller_carry_back: String?
    public var lender_seller_carry_back_2: String?
    public var lender_state: String?
    public var lender_state_2: String?
    public var lender_zip: String?
    public var lender_zip_2: String?
    public var lender_zip_extended: String?
    public var lender_zip_extended_2: String?
    public var loading_platform: String?
    public var loading_platform_sqft: String?
    public var longitude: String?
    public var lot_1: String?
    public var lot_2: String?
    public var lot_3: String?
    public var lot_sqft: String?
    public var market_improvement_percent: String?
    public var market_improvement_value: String?
    public var market_land_value: String?
    public var market_value_year: String?
    public var match_type: String?
    public var media_room: String?
    public var metro_division: String?
    public var middle_name: String?
    public var middle_name_2: String?
    public var middle_name_3: String?
    public var middle_name_4: String?
    public var milkhouse: String?
    public var milkhouse_sqft: String?
    public var minor_civil_division_code: String?
    public var minor_civil_division_name: String?
    public var mobile_home_hookup: String?
    public var mortgage_amount: String?
    public var mortgage_amount_2: String?
    public var mortgage_due_date: String?
    public var mortgage_due_date_2: String?
    public var mortgage_interest_rate: String?
    public var mortgage_interest_rate_type: String?
    public var mortgage_lender_code: String?
    public var mortgage_rate_2: String?
    public var mortgage_recording_date: String?
    public var mortgage_recording_date_2: String?
    public var mortgage_term: String?
    public var mortgage_term_2: String?
    public var mortgage_term_type: String?
    public var mortgage_term_type_2: String?
    public var mortgage_type: String?
    public var mortgage_type_2: String?
    public var msa_code: String?
    public var msa_name: String?
    public var mud_room: String?
    public var multi_parcel_flag: String?
    public var name_title_company: String?
    public var neighborhood_code: String?
    public var number_of_buildings: String?
    public var office: String?
    public var office_sqft: String?
    public var other_tax_exemption: String?
    public var outdoor_kitchen_fireplace: String?
    public var overhead_door: String?
    public var owner_full_name: String?
    public var owner_full_name_2: String?
    public var owner_full_name_3: String?
    public var owner_full_name_4: String?
    public var owner_occupancy_status: String?
    public var ownership_transfer_date: String?
    public var ownership_transfer_doc_number: String?
    public var ownership_transfer_transaction_id: String?
    public var ownership_type: String?
    public var ownership_type_2: String?
    public var ownership_vesting_relation_code: String?
    public var parcel_account_number: String?
    public var parcel_map_book: String?
    public var parcel_map_page: String?
    public var parcel_number_alternate: String?
    public var parcel_number_formatted: String?
    public var parcel_number_previous: String?
    public var parcel_number_year_added: String?
    public var parcel_number_year_change: String?
    public var parcel_raw_number: String?
    public var parcel_shell_record: String?
    public var parking_spaces: String?
    public var patio_area: String?
    public var phase_name: String?
    public var plumbing_fixtures_count: String?
    public var pole_struct: String?
    public var pole_struct_sqft: String?
    public var pond: String?
    public var pool: String?
    public var pool_area: String?
    public var poolhouse: String?
    public var poolhouse_sqft: String?
    public var porch: String?
    public var porch_area: String?
    public var poultry_house: String?
    public var poultry_house_sqft: String?
    public var previous_assessed_value: String?
    public var prior_sale_amount: String?
    public var prior_sale_date: String?
    public var property_address_carrier_route_code: String?
    public var property_address_city: String?
    public var property_address_full: String?
    public var property_address_house_number: String?
    public var property_address_post_direction: String?
    public var property_address_pre_direction: String?
    public var property_address_state: String?
    public var property_address_street_name: String?
    public var property_address_street_suffix: String?
    public var property_address_unit_designator: String?
    public var property_address_unit_value: String?
    public var property_address_zip_4: String?
    public var property_address_zipcode: String?
    public var publication_date: String?
    public var quarter: String?
    public var quarter_quarter: String?
    public var quonset: String?
    public var quonset_sqft: String?
    public var range: String?
    public var recording_date: String?
    public var roof_cover: String?
    public var roof_frame: String?
    public var rooms: String?
    public var rv_parking: String?
    public var safe_room: String?
    public var sale_amount: String?
    public var sale_date: String?
    public var sauna: String?
    public var section: String?
    public var security_alarm: String?
    public var senior_tax_exemption: String?
    public var sewer_type: String?
    public var shed: String?
    public var shed_sqft: String?
    public var silo: String?
    public var silo_sqft: String?
    public var sitting_room: String?
    public var situs_county: String?
    public var situs_state: String?
    public var sound_system: String?
    public var sports_court: String?
    public var sprinklers: String?
    public var stable: String?
    public var stable_sqft: String?
    public var storage_building: String?
    public var storage_building_sqft: String?
    public var stories_number: String?
    public var storm_shelter: String?
    public var storm_shutter: String?
    public var structure_style: String?
    public var study: String?
    public var subdivision: String?
    public var suffix: String?
    public var suffix_2: String?
    public var suffix_3: String?
    public var suffix_4: String?
    public var sunroom: String?
    public var tax_assess_year: String?
    public var tax_billed_amount: String?
    public var tax_delinquent_year: String?
    public var tax_fiscal_year: String?
    public var tax_jurisdiction: String?
    public var tax_rate_area: String?
    public var tennis_court: String?
    public var topography_code: String?
    public var total_market_value: String?
    public var township: String?
    public var tract_number: String?
    public var transfer_amount: String?
    public var trust_description: String?
    public var unit_count: String?
    public var upper_floors_sqft: String?
    public var utility: String?
    public var utility_building: String?
    public var utility_building_sqft: String?
    public var utility_sqft: String?
    public var veteran_tax_exemption: String?
    public var view_description: String?
    public var water_feature: String?
    public var water_service_type: String?
    public var wet_bar: String?
    public var widow_tax_exemption: String?
    public var width_linear_footage: String?
    public var wine_cellar: String?
    public var year_built: String?
    public var zoning: String?

}


