import Foundation

public class FinancialAttributes: Decodable {
   public var assessed_improvement_percent: String?
   public var assessed_improvement_value: String?
   public var assessed_land_value: String?
   public var assessed_value: String?
   public var assessor_last_update: String?
   public var assessor_taxroll_update: String?
   public var contact_city: String?
   public var contact_crrt: String?
   public var contact_full_address: String?
   public var contact_house_number: String?
   public var contact_mail_info_format: String?
   public var contact_mail_info_privacy: String?
   public var contact_mailing_county: String?
   public var contact_mailing_fips: String?
   public var contact_post_direction: String?
   public var contact_pre_direction: String?
   public var contact_state: String?
   public var contact_street_name: String?
   public var contact_suffix: String?
   public var contact_unit_designator: String?
   public var contact_value: String?
   public var contact_zip: String?
   public var contact_zip4: String?
   public var deed_document_book: String?
   public var deed_document_number: String?
   public var deed_document_page: String?
   public var deed_owner_first_name: String?
   public var deed_owner_first_name2: String?
   public var deed_owner_first_name3: String?
   public var deed_owner_first_name4: String?
   public var deed_owner_full_name: String?
   public var deed_owner_full_name2: String?
   public var deed_owner_full_name3: String?
   public var deed_owner_full_name4: String?
   public var deed_owner_last_name: String?
   public var deed_owner_last_name2: String?
   public var deed_owner_last_name3: String?
   public var deed_owner_last_name4: String?
   public var deed_owner_middle_name: String?
   public var deed_owner_middle_name2: String?
   public var deed_owner_middle_name3: String?
   public var deed_owner_middle_name4: String?
   public var deed_owner_suffix: String?
   public var deed_owner_suffix2: String?
   public var deed_owner_suffix3: String?
   public var deed_owner_suffix4: String?
   public var deed_sale_date: String?
   public var deed_sale_price: String?
   public var deed_transaction_id: String?
   public var disabled_tax_exemption: String?
   public var financial_history: [FinancialHistoryEntry]?
   public var first_name: String?
   public var first_name_2: String?
   public var first_name_3: String?
   public var first_name_4: String?
   public var homeowner_tax_exemption: String?
   public var last_name: String?
   public var last_name_2: String?
   public var last_name_3: String?
   public var last_name_4: String?
   public var market_improvement_percent: String?
   public var market_improvement_value: String?
   public var market_land_value: String?
   public var market_value_year: String?
   public var match_type: String?
   public var middle_name: String?
   public var middle_name_2: String?
   public var middle_name_3: String?
   public var middle_name_4: String?
   public var other_tax_exemption: String?
   public var owner_full_name: String?
   public var owner_full_name_2: String?
   public var owner_full_name_3: String?
   public var owner_full_name_4: String?
   public var ownership_transfer_date: String?
   public var ownership_transfer_doc_number: String?
   public var ownership_transfer_transaction_id: String?
   public var ownership_type: String?
   public var ownership_type_2: String?
   public var previous_assessed_value: String?
   public var prior_sale_amount: String?
   public var prior_sale_date: String?
   public var sale_amount: String?
   public var sale_date: String?
   public var senior_tax_exemption: String?
   public var suffix: String?
   public var suffix_2: String?
   public var suffix_3: String?
   public var suffix_4: String?
   public var tax_assess_year: String?
   public var tax_billed_amount: String?
   public var tax_delinquent_year: String?
   public var tax_fiscal_year: String?
   public var tax_rate_area: String?
   public var total_market_value: String?
   public var trust_description: String?
   public var veteran_tax_exemption: String?
   public var widow_tax_exemption: String?
}
